### ISSUE TITLE
Mapping UniProt IDs to HGNC symbols

### ISSUE THREAD

**Issue by ddomingof** [bio2bel/reactome#1]
@cthoyt should we create another table with the mapping to HGNCs? or should we assume that is already available using PyHGNC?

**Comment by cthoyt** [comment]
Assume that's available through PyHGNC. Depending on your use case, you might even want to import PyHGNC and use some of its functions

**Comment by ddomingof** [comment]
Use PyHGNC to get Rat/Mouse/Human mapping
