### ISSUE TITLE
How to get pathways?

### ISSUE THREAD

**Issue by Chrizsly** [bio2bel/reactome#15]
Hi,

installed and downloaded bio2bel as described in the guide, took a while, but seemed successful: 

```python
import bio2bel_reactome
reactome_manager = bio2bel_reactome.Manager()
reactome_manager.populate()
Loading species: 100%|██████████| 16/16 [00:00<00:00, 223.05it/s]
Loading pathways: 100%|██████████| 21012/21012 [00:14<00:00, 1420.69it/s]
Loading pathway hierarchy: 100%|██████████| 21198/21198 [00:49<00:00, 429.72it/s]
100%|██████████| 43547/43547 [00:38<00:00, 1125.46it/s]
Insert HGNC data into database
Loading proteins: 100%|██████████| 129189/129189 [1:45:54<00:00, 20.33it/s] 
missing 415 hgncs
InChIs: 100%|██████████| 94015/94015 [00:07<00:00, 13395.49it/s]
Compounds: 100%|██████████| 141397/141397 [00:32<00:00, 4289.34it/s]
Secondaries: 100%|██████████| 19267/19267 [00:00<00:00, 813452.80it/s]
Loading chemicals:  84%|████████▍ | 25067/29924 [00:19<00:03, 1246.43it/s]545111 was not found by chebi manager
545111 was not found by chebi manager
545111 was not found by chebi manager
545111 was not found by chebi manager
545111 was not found by chebi manager
545111 was not found by chebi manager
Loading chemicals: 100%|██████████| 29924/29924 [00:23<00:00, 1276.91it/s]`
```
I am not sure how to proceed from here. I have a list of genes I would like to pass on to reactome to identify pathways. Any help would be appreciated.

Best

**Comment by cthoyt** [comment]
There’s a function that will directly do some hyper geometric and related statistical tests for enrichment
@ddomingof let’s check the docs and make sure there are some tutorials on programmatic use of the manager. Maybe we can add to compath_utils so there’s also a CLI entry point for enrichment analysis on a gene list

**Comment by ddomingof** [comment]
Hi @Chrizsly, like @cthoyt said there is a function for that but if you want a simple solution you can put your gene list in ComPath (https://compath.scai.fraunhofer.de/)

**Comment by ddomingof** [comment]
If you want to do it programatically now you can install compath from PyPi
and you import "perform_hypergeometric_test" from compath.utils

You have to pass to this function your gene set that you want to test and the pathway dict with the genesets for reactome and finally the gene_universe which should be 40000
(see the function) 
perform_hypergeometric_test(gene_set, manager_pathways_dict, gene_universe=44000,)

**Comment by Chrizsly** [comment]
Thanks for the quick reply. The online tool is quite nice, but I will have to analyse a few hundred data sets, so doing this manually wont be an option :D 
I now used 
`python3 -m pip install bio2bel_reactome`

to install the latest reactome DB. Then installing compath:
`python3 -m pip install compath`
when running:
`python3 -m compath populate`
i get the  following error code:

> version conflict in reactome

**Comment by ddomingof** [comment]
The version that you installed first from bio2bel_reactome might not be compatible with current version of ComPath. I think it is easier if I send you the code

**Comment by ddomingof** [comment]
Comment: this will give you a dictionary from pathways to gene sets in reactome
```
import bio2bel_reactome
reactome_manager = bio2bel_reactome.Manager() 
reactome_gene_sets = reactome_manager.export_gene_sets()

```
This will do the enrichment analysis
```
from scipy.stats import fisher_exact
from sqlalchemy import and_
from statsmodels.sandbox.stats.multicomp import multipletests

def perform_hypergeometric_test(gene_set, reactome_gene_sets, gene_universe=40000, apply_threshold=False, threshold=0.05):
    """Perform hypergeometric tests.

    :param set[str] gene_set: gene set to test against pathway
    :param int gene_universe: number of HGNC symbols
    :param Optional[bool] apply_threshold: return only significant pathways
    :param Optional[float] threshold: significance threshold (by default 0.05)
    :rtype: dict[str,dict[str,dict]]
    :return: manager_pathways_dict with p value info
    """
    manager_p_values = dict()

        for pathway_id, gene_set in reactome_gene_sets.items():
            test_table = _prepare_hypergeometric_test(gene_set, gene_set, gene_universe)

            oddsratio, pvalue = fisher_exact(test_table, alternative='greater')

            manager_p_values[manager_name, pathway_id] = pvalue

    # Split the dictionary into names_id tuples and p values to keep the same order
    manager_pathway_id, p_values = zip(*manager_p_values.items())
    correction_test = multipletests(p_values, method='fdr_bh')

    q_values = correction_test[1]

    # Update original dict with p value corrections
    for i, (manager_name, pathway_id) in enumerate(manager_pathway_id):

        q_value = round(q_values[i], 4)

        # Print the results
        if apply_threshold and q_value < threshold:
            print(f'{pathway_id} is significant with a q value of {q_value}'

```

**Comment by ddomingof** [comment]
The code should work (maybe not since I coded it directly on the github page) and you would only have to change the first part where you define your 'gene_set' variable

**Comment by Chrizsly** [comment]
Thanks, seems almost to work. The following is not defined:
`_prepare_hypergeometric_test(gene_set, gene_set, gene_universe)`
any ideas?

**Comment by ddomingof** [comment]
Sorry I forgot:


```
import numpy as np
def _prepare_hypergeometric_test(query_gene_set, pathway_gene_set, gene_universe):
    """Prepare the matrix for hypergeometric test calculations.

    :param set[str] query_gene_set: gene set to test against pathway
    :param set[str] pathway_gene_set: pathway gene set
    :param int gene_universe: number of HGNC symbols
    :rtype: numpy.ndarray
    :return: 2x2 matrix
    """
    return np.array(
        [[len(query_gene_set.intersection(pathway_gene_set)),
          len(query_gene_set.difference(pathway_gene_set))
          ],
         [len(pathway_gene_set.difference(query_gene_set)),
          gene_universe - len(pathway_gene_set.union(query_gene_set))
          ]
         ]
    )
```

**Comment by ddomingof** [comment]
It all comes from here:
https://github.com/ComPath/ComPath/blob/master/src/compath/utils.py

**Comment by Chrizsly** [comment]
Ok, copied both functions into my code, when calling perform_, I get the following error:
` for pathway_id, pathway_dict in pathways.items():`

my gene list is a list containing str, the variable: manager_pathways_dict = reactome_gene_sets, which is a dict of size 2300.

**Comment by ddomingof** [comment]
Can you please send the error?

**Comment by Chrizsly** [comment]
`for pathway_id, pathway_dict in pathways.items():

AttributeError: 'set' object has no attribute 'items'`

**Comment by ddomingof** [comment]
I am lost now where is this code now? Because it is not in the one I sent. Can you post here the entire thing or just email it to me?

**Comment by Chrizsly** [comment]
Ok, the code now runs when I assign all variables that are input to the function: perform_hypergeometric_test. However, when I want to do the following:
`perform_hypergeometric_test(gene_set, reactome_gene_sets, gene_universe=44000,apply_threshold=False,threshold=0.05)`

I get the following error: 

`perform_hypergeometric_test(gene_set, reactome_gene_sets, gene_universe=44000,apply_threshold=False,threshold=0.05)
Traceback (most recent call last):

  File "<ipython-input-74-e3c45b982724>", line 1, in <module>
    perform_hypergeometric_test(gene_set, reactome_gene_sets, gene_universe=44000,apply_threshold=False,threshold=0.05)

  File "<ipython-input-63-9a686397cd58>", line 18, in perform_hypergeometric_test
    manager_p_values[manager_name, pathway_id] = pvalue

UnboundLocalError: local variable 'manager_name' referenced before assignment`

Weird - when I just execute everything inside the function and calling it directly, the code runs and I get a list of p-values and pathways

**Comment by cthoyt** [comment]
Idk why all of the manager stuff was in there @ddomingof. was this function written as a closure inside a loop over several managers? I make an edit to the example above to fix it

**Comment by cthoyt** [comment]
Also there was a variable that got overwritten... `gene_set` was used both as the input to the function and also as the loop variable. I fixed that too

**Comment by Chrizsly** [comment]
Right, are you copying the code here? That would really help

**Comment by cthoyt** [comment]
@Chrizsly see updated https://github.com/bio2bel/reactome/issues/15#issuecomment-579203010

**Comment by Chrizsly** [comment]
got it. new error:
`
  File "<ipython-input-85-8d459527447f>", line 4, in <module>
    test_table = _prepare_hypergeometric_test(query_gene_set, gene_set, gene_universe)

  File "<ipython-input-82-b525b075f123>", line 46, in _prepare_hypergeometric_test
    len(query_gene_set.intersection(pathway_gene_set)),

AttributeError: 'list' object has no attribute 'intersection'`


the variable query_gene_list is a list of some hundred genes, type(value) is str. Is that the right format?

**Comment by ddomingof** [comment]
Thats easy to fix, you can simply convert the list to a set before passing it to the functino

**Comment by Chrizsly** [comment]
just did that! :) thanks for the help, code now runs perfectly fine!

**Comment by cthoyt** [comment]
Happy hunting @Chrizsly

**Comment by Chrizsly** [comment]
One more question: 
where would I find the number of genes that were mapped from my list to a certain pathway. And do we know the max number of genes assigend to a pathway from the DB?

**Comment by cthoyt** [comment]
The code that's calculating that number is here already, but it's not getting returned. For a given query gene set, you can do this:

```python
my_gene_set = { ... }
for pathway_id, gene_set in reactome_gene_sets.items():
    mapped = gene_set.intersect(my_gene_set)
    print(pathway_id, len(mapped))
```

If you want to get the max for any pathway, you could do it in an incredible one-liner:
```python
my_gene_set = { ... }
max_mapped = max(
    len(gene_set.intersect(my_gene_set))
    for gene_set in reactome_gene_sets.values()
)

**Comment by Chrizsly** [comment]
perfect, modified it a bit, but this is working for me now :) thanks a lot!
