### ISSUE TITLE
Dependency conflict, pybel package

### ISSUE THREAD

**Issue by choooze** [bio2bel/reactome#18]
Hello guys.

You have the next dependency:
pybel==0.14.1

And 
    'bio2bel_chebi>=0.1.0',

If you will take a look at the dependency list of a latest bio2bel_chebi package (https://github.com/bio2bel/chebi/blob/master/setup.py#L33)
You will see there:
    'pybel>=0.13.1,<0.14.0'

So there is now way to install the current version of bio2bel_reactome due to a dependency conflict.

**Comment by ddomingof** [comment]
@cthoyt can youu check this?

**Comment by cthoyt** [comment]
This has been fixed in #17 but the PR hasn't been finished yet

**Comment by cthoyt** [comment]
Closed by #17
